name: "Build FAP"

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build with uFBT
        uses: flipperdevices/flipperzero-ufbt-action@v0.1.2
        with:
          app-dir: custom-ble-adv   # <-- Use hyphen (-) instead of underscore (_)
        id: build-app

      - name: Upload .fap Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flipper-fap
          path: '**/*.fap'          # Search subdirectories for the compiled file
