name: "Build FAP"

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build with uFBT
        uses: flipperdevices/flipperzero-ufbt-action@v0.1.2
        id: build-app

      - name: Upload .fap Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flipper-fap
          path: '*.fap'
